const { createSubmissionReadSnapshot } = require("./submission-read-snapshot");

function batchError(code, message) { const error = new Error(message); error.code = code; return error; }

// Owns the immutable submission read model. Commands must create a fresh
// snapshot before mutation; this module never accepts a facade callback.
function createSubmissionQuery(deps) {
  function itemIdentity(item) { return [item.articleId, item.targetPlatformId, item.publicationId || null, item.attemptId || null].join("\0"); }
  function articleSelectionKey(item) { return item.clientId + "\0" + item.articleId; }
  function createReadSnapshot(input) { return createSubmissionReadSnapshot(deps, input); }
  function publicationForBatchItem(item) { if (!item.publicationId || !item.attemptId || typeof deps.publicationLedger.get !== "function") return null; try { return deps.publicationLedger.get(item.publicationId); } catch (_) { return null; } }
  function snapshotPublication(snapshot, item) { if (!item.publicationId || !item.attemptId) return null; if (!snapshot.publicationsById.has(item.publicationId)) snapshot.publicationsById.set(item.publicationId, publicationForBatchItem(item)); return snapshot.publicationsById.get(item.publicationId); }
  function snapshotSidecar(snapshot, entry) { if (!entry) return null; if (!snapshot.sidecarsByItem.has(entry.itemKey)) snapshot.sidecarsByItem.set(entry.itemKey, deps.readSidecar(entry.item)); return snapshot.sidecarsByItem.get(entry.itemKey); }
  function articleSubmissionItems(selections, snapshot) {
    const readSnapshot = snapshot || createReadSnapshot(); const found = []; const seen = new Set();
    new Set(selections.map(articleSelectionKey)).forEach(function(key) { (readSnapshot.itemsByArticle.get(key) || []).forEach(function(entry) {
      const batch = entry.batch; const item = entry.item; const identityKey = (item.publicationId || batch.id + ":" + item.targetPlatformId + ":" + item.articleId) + "\0" + (item.attemptId || "");
      if (seen.has(identityKey)) return; seen.add(identityKey);
      const record = snapshotPublication(readSnapshot, item); const latest = deps.latestAttempt(record); const sidecar = snapshotSidecar(readSnapshot, entry); const pair = deps.inspectSubmissionPair(item, batch, sidecar, { rootDir: deps.rootDir, record });
      const cleaned = ["failed-cleaned", "published-cleaned", "cancelled-cleaned"]; const status = cleaned.includes(item.status) ? item.status : record ? record.status : item.publicationStatus || item.status;
      if (record && (record.titleSnapshot === undefined || record.titleSnapshot === null) && typeof deps.publicationLedger.ensureTitleSnapshot === "function") { try { deps.publicationLedger.ensureTitleSnapshot(record.publicationId, deps.getArticle(batch.clientId, item.articleId).title); } catch (_) {} }
      const safe = { clientId: batch.clientId, articleId: item.articleId, batchId: batch.id, targetPlatformId: item.targetPlatformId, publicationId: item.publicationId || null, attemptId: item.attemptId || null, contentHash: item.contentHash || (sidecar && sidecar.contentHash) || null, status, unchanged: pair.pairState === "intact", pairState: pair.pairState, identityMatched: pair.identityMatched, contentMatched: pair.contentMatched, mainExists: pair.mainExists, sidecarExists: pair.sidecarExists };
      found.push({ safe, item, batch, record, sidecar, latest });
    }); }); return found;
  }
  function locateArticleSubmissionItem(action, snapshot) { const readSnapshot = snapshot || createReadSnapshot({ batchId: action.batchId }); const key = (action.publicationId || action.batchId + ":" + action.targetPlatformId + ":" + action.articleId) + "\0" + (action.attemptId || ""); const indexed = readSnapshot.itemsByIdentity.get(key); const entries = indexed ? articleSubmissionItems([{ clientId: action.clientId, articleId: action.articleId }], readSnapshot).filter(function(entry) { return entry.item === indexed.item; }) : articleSubmissionItems([{ clientId: action.clientId, articleId: action.articleId }], readSnapshot); return entries.find(function(entry) { return entry.safe.batchId === action.batchId && entry.safe.targetPlatformId === action.targetPlatformId && (action.publicationId && action.attemptId ? entry.safe.publicationId === action.publicationId && entry.safe.attemptId === action.attemptId : entry.safe.articleId === action.articleId); }); }
  function actionBindingFingerprint(entry, action) { const record = entry.record || {}; return deps.hash(JSON.stringify({ action: action.action, clientId: entry.safe.clientId, articleId: entry.safe.articleId, batchId: entry.safe.batchId, targetPlatformId: entry.safe.targetPlatformId, publicationId: entry.safe.publicationId, attemptId: entry.safe.attemptId, publicationStatus: entry.safe.status, contentHash: entry.safe.contentHash, sidecarAttemptId: entry.sidecar && entry.sidecar.attemptId || null, unchanged: entry.safe.unchanged, pairState: entry.safe.pairState, identityMatched: entry.safe.identityMatched, contentMatched: entry.safe.contentMatched, recordStatus: record.status || null, attempts: Array.isArray(record.attempts) ? record.attempts.map(function(attempt) { return { attemptId: attempt.attemptId, status: attempt.status }; }) : [] })); }
  function evaluation(action, entry, allowed, reasonCode, resolvedState) { const safe = Object.assign({}, entry && entry.safe || {}, { reasonCode: reasonCode || null }); return { allowed: allowed === true, action: action.action, reasonCode: reasonCode || null, resolvedState: resolvedState || safe, bindingFingerprint: entry ? actionBindingFingerprint(entry, action) : null, entry: entry || null }; }
  function evaluateItemAction(action, snapshot) {
    if (!action || typeof action !== "object" || !["cancel", "cleanup", "cleanupPublishedLocal", "cleanupCancelledLocal"].includes(action.action)) return { allowed: false, action: action && action.action || null, reasonCode: "SUBMISSION_ACTION_INVALID", resolvedState: null, bindingFingerprint: null, entry: null };
    const entry = locateArticleSubmissionItem(action, snapshot); if (!entry || !entry.item || !entry.batch) return { allowed: false, action: action.action, reasonCode: "SUBMISSION_QUEUE_ITEM_NOT_FOUND", resolvedState: null, bindingFingerprint: null, entry: null };
    const current = actionBindingFingerprint(entry, action); if (action.evaluationFingerprint && action.evaluationFingerprint !== current) return evaluation(action, entry, false, "SUBMISSION_ACTION_STALE");
    if (!["failed-cleaned", "published-cleaned", "cancelled-cleaned"].includes(entry.safe.status) && !["intact", "both_absent", "main_absent", "sidecar_absent"].includes(entry.safe.pairState)) return evaluation(action, entry, false, entry.safe.pairState === "identity_conflict" ? "SUBMISSION_IDENTITY_CONFLICT" : entry.safe.pairState === "content_changed" ? "SUBMISSION_CONTENT_CHANGED" : "SUBMISSION_QUEUE_CHANGED");
    if (["both_absent", "main_absent", "sidecar_absent"].includes(entry.safe.pairState) && entry.safe.identityMatched !== true) return evaluation(action, entry, false, "SUBMISSION_IDENTITY_CONFLICT");
    if (action.action === "cancel" && entry.safe.status === "cancelled") return evaluation(action, entry, false, "SUBMISSION_ALREADY_CANCELLED");
    if (["failed-cleaned", "published-cleaned", "cancelled-cleaned"].includes(entry.safe.status)) return evaluation(action, entry, true, null);
    if (action.action === "cancel") { if (entry.safe.status !== "queued") return evaluation(action, entry, false, entry.safe.status === "failed" ? "PUBLICATION_STATUS_NOT_QUEUED" : "ARTICLE_SUBMISSION_ACTIVE"); if (entry.record && (entry.record.status !== "queued" || !entry.latest || entry.latest.attemptId !== action.attemptId)) return evaluation(action, entry, false, "PUBLICATION_ATTEMPT_MISMATCH"); if (entry.latest && entry.latest.status !== "queued") return evaluation(action, entry, false, "PUBLICATION_REMOTE_STARTED"); return evaluation(action, entry, true, null); }
    const expected = action.action === "cleanup" ? "failed" : action.action === "cleanupPublishedLocal" ? "published" : "cancelled"; if (entry.safe.status !== expected) return evaluation(action, entry, false, ["queued", "submitting", "submitted", "uncertain"].includes(entry.safe.status) ? "ARTICLE_SUBMISSION_ACTIVE" : "PUBLICATION_STATUS_NOT_FAILED");
    if (entry.record) { if (entry.record.status !== expected) return evaluation(action, entry, false, action.action === "cleanup" ? "PUBLICATION_STATUS_NOT_FAILED" : "PUBLICATION_ATTEMPT_MISMATCH"); if (!Array.isArray(entry.record.attempts) || !entry.record.attempts.find(function(attempt) { return attempt.attemptId === action.attemptId && attempt.status === expected; })) return evaluation(action, entry, false, "PUBLICATION_ATTEMPT_MISMATCH"); } else if (entry.safe.publicationId) return evaluation(action, entry, false, "PUBLICATION_RECORD_MISSING");
    return evaluation(action, entry, true, null);
  }
  function reconcileBatch(batchId, snapshot) {
    const readSnapshot = snapshot || createReadSnapshot({ batchId }); let batch = readSnapshot.batchesById.get(batchId); if (!batch) throw batchError("SUBMISSION_BATCH_NOT_FOUND", "Submission batch was not found"); const reconciled = []; const transitions = [];
    (batch.items || []).forEach(function(item) { const copy = Object.assign({}, item); const entry = readSnapshot.itemsByIdentity.get((item.publicationId || batch.id + ":" + item.targetPlatformId + ":" + item.articleId) + "\0" + (item.attemptId || "")); const record = snapshotPublication(readSnapshot, item); const latest = deps.latestAttempt(record); const sidecar = snapshotSidecar(readSnapshot, entry); const pair = deps.inspectSubmissionPair(item, batch, sidecar, { rootDir: deps.rootDir, record: record || null });
      Object.assign(copy, { unchanged: pair.pairState === "intact", pairState: pair.pairState, identityMatched: pair.identityMatched, contentMatched: pair.contentMatched, mainExists: pair.mainExists, sidecarExists: pair.sidecarExists });
      if (!item.publicationId || !item.attemptId) { const evaluation = evaluateItemAction({ clientId: batch.clientId, articleId: item.articleId, batchId: batch.id, targetPlatformId: item.targetPlatformId, action: "cancel" }, readSnapshot); Object.assign(copy, { reconciledStatus: item.status, publicationStatus: item.status, canCancel: !!evaluation.allowed, canCleanup: false, actionFingerprint: evaluation.bindingFingerprint }); if (!copy.canCancel) copy.reasonCode = evaluation.reasonCode || "SUBMISSION_QUEUE_CHANGED"; reconciled.push(copy); return; }
      if (!record || !latest || record.platformId && record.platformId !== item.targetPlatformId) { copy.reconciledStatus = "conflict"; copy.reasonCode = !record ? "PUBLICATION_RECORD_MISSING" : "PUBLICATION_PLATFORM_MISMATCH"; reconciled.push(copy); return; }
      Object.assign(copy, { reconciledStatus: record.status, publicationStatus: record.status, errorCode: latest.errorCode || item.errorCode || null }); const locallyCleaned = ["failed-cleaned", "published-cleaned", "cancelled-cleaned"].includes(item.status); if (item.status !== record.status && !locallyCleaned) transitions.push({ identity: { publicationId: item.publicationId, attemptId: item.attemptId, targetPlatformId: item.targetPlatformId }, transition: { status: record.status, publicationStatus: record.status, errorCode: latest.errorCode || undefined, remoteId: latest.remoteId || undefined, remoteUrl: latest.remoteUrl || undefined, reasonCode: latest.reasonCode || undefined } });
      const input = { clientId: batch.clientId, articleId: item.articleId, batchId: batch.id, targetPlatformId: item.targetPlatformId, publicationId: item.publicationId, attemptId: item.attemptId }; const evaluations = { cancel: record.status === "queued" && evaluateItemAction(Object.assign({}, input, { action: "cancel" }), readSnapshot), cleanup: record.status === "failed" && evaluateItemAction(Object.assign({}, input, { action: "cleanup" }), readSnapshot), published: record.status === "published" && evaluateItemAction(Object.assign({}, input, { action: "cleanupPublishedLocal" }), readSnapshot), cancelled: record.status === "cancelled" && evaluateItemAction(Object.assign({}, input, { action: "cleanupCancelledLocal" }), readSnapshot) };
      Object.assign(copy, { canCancel: !!(evaluations.cancel && evaluations.cancel.allowed), canCleanup: !!(evaluations.cleanup && evaluations.cleanup.allowed), canCleanupPublished: !!(evaluations.published && evaluations.published.allowed), canCleanupCancelled: !!(evaluations.cancelled && evaluations.cancelled.allowed) }); const selected = evaluations.cancel || evaluations.cleanup || evaluations.published || evaluations.cancelled; copy.actionFingerprint = selected && selected.allowed ? selected.bindingFingerprint : null; if (!copy.canCancel && !copy.canCleanup && !copy.canCleanupPublished && !copy.canCleanupCancelled && selected) copy.reasonCode = selected.reasonCode; reconciled.push(copy);
    });
    if (transitions.length) { try { batch = deps.batchStore.reconcile(batch.id, transitions); } catch (_) { transitions.forEach(function(change) { const conflict = reconciled.find(function(candidate) { return candidate.publicationId === change.identity.publicationId && candidate.attemptId === change.identity.attemptId && candidate.targetPlatformId === change.identity.targetPlatformId; }); if (conflict) { conflict.reconciledStatus = "conflict"; conflict.reasonCode = "SUBMISSION_STATUS_CONFLICT"; } }); } }
    const states = new Map(reconciled.map(function(candidate) { return [itemIdentity(candidate), candidate]; })); const items = batch.items.map(function(item) { const state = states.get(itemIdentity(item)); return state ? Object.assign({}, item, { reconciledStatus: state.reconciledStatus, unchanged: state.unchanged, pairState: state.pairState, identityMatched: state.identityMatched, contentMatched: state.contentMatched, mainExists: state.mainExists, sidecarExists: state.sidecarExists, canCancel: state.canCancel, canCleanup: state.canCleanup, canCleanupPublished: state.canCleanupPublished, canCleanupCancelled: state.canCleanupCancelled, reasonCode: state.reasonCode, publicationStatus: state.publicationStatus || item.publicationStatus, errorCode: state.errorCode || item.errorCode || null }) : item; }); return { batch: Object.assign({}, batch, { items }), items: reconciled };
  }
  function actionReasonMessage(reasonCode) { const messages = { SUBMISSION_ACTION_STALE: "动作计划已过期，请重新预览。", SUBMISSION_IDENTITY_CONFLICT: "本地队列身份不完整或不匹配。", SUBMISSION_CONTENT_CHANGED: "队列文件内容已变化。", SUBMISSION_QUEUE_CHANGED: "队列文件状态已变化。", PUBLICATION_REMOTE_STARTED: "投稿已经开始，不能撤销。", ARTICLE_SUBMISSION_ACTIVE: "投稿正在进行，不能撤销。", SUBMISSION_ALREADY_CANCELLED: "该项目已经撤销。" }; return messages[reasonCode] || "当前项目不能执行该操作。"; }
  function buildActionPlan(batchId, action, snapshot, reconciledResult) { if (typeof batchId !== "string" || !batchId) throw batchError("CONTENT_SUBMISSION_BATCH_INPUT_INVALID", "Batch id is required"); if (action !== "cancel") throw batchError("SUBMISSION_ACTION_INVALID", "Submission action is invalid"); const readSnapshot = snapshot || createReadSnapshot({ batchId }); const reconciled = reconciledResult || reconcileBatch(batchId, readSnapshot); const batch = reconciled.batch; const planSnapshot = reconciledResult ? createReadSnapshot({ batches: [batch] }) : readSnapshot; if (reconciledResult) { readSnapshot.publicationsById.forEach(function(value, key) { planSnapshot.publicationsById.set(key, value); }); readSnapshot.sidecarsByItem.forEach(function(value, key) { planSnapshot.sidecarsByItem.set(key, value); }); }
    const items = batch.items.map(function(item) { const checked = evaluateItemAction({ clientId: batch.clientId, articleId: item.articleId, batchId: batch.id, targetPlatformId: item.targetPlatformId, publicationId: item.publicationId, attemptId: item.attemptId, action }, planSnapshot); return { articleId: item.articleId, targetPlatformId: item.targetPlatformId, publicationId: item.publicationId || null, attemptId: item.attemptId || null, action, allowed: checked.allowed, reasonCode: checked.reasonCode || null, reasonMessage: checked.allowed ? null : actionReasonMessage(checked.reasonCode), fingerprint: checked.bindingFingerprint || null }; }); const revision = deps.hash(JSON.stringify({ id: batch.id, clientId: batch.clientId, updatedAt: batch.updatedAt || null, status: batch.status, items: batch.items })); const planId = deps.hash(JSON.stringify({ batchId: batch.id, action, revision, items: items.map(function(item) { return [item.articleId, item.targetPlatformId, item.publicationId, item.attemptId, item.fingerprint, item.allowed]; }) })); return { batchId: batch.id, clientId: batch.clientId, action, revision, planId, fingerprint: planId, items, allowedCount: items.filter(function(item) { return item.allowed; }).length, blockedCount: items.filter(function(item) { return !item.allowed; }).length };
  }
  function getBatch(batchId) { return reconcileBatch(batchId).batch; }
  function listBatches(clientId) { const snapshot = createReadSnapshot(); return snapshot.batches.filter(function(batch) { return !clientId || batch.clientId === clientId; }).map(function(batch) { const result = reconcileBatch(batch.id, snapshot); const plan = buildActionPlan(batch.id, "cancel", snapshot, result); const planned = new Map(plan.items.map(function(candidate) { return [itemIdentity(candidate), candidate]; })); return Object.assign({}, result.batch, { actionPlan: plan, items: result.batch.items.map(function(item) { const candidate = planned.get(itemIdentity(item)); return Object.assign({}, item, { canCancel: !!(candidate && candidate.allowed), actionFingerprint: candidate && candidate.fingerprint || null, reasonCode: candidate && !candidate.allowed ? candidate.reasonCode : item.reasonCode }); }) }); }); }
  function previewArticleRemovalImpact(value) { const selections = value && (value.selections || value.articles); if (!Array.isArray(selections) || !selections.length) throw batchError("CONTENT_INPUT_INVALID", "At least one article is required"); const normalized = selections.map(function(item) { if (!item || typeof item.clientId !== "string" || !item.clientId.trim() || typeof item.articleId !== "string" || !item.articleId.trim()) throw batchError("CONTENT_INPUT_INVALID", "Article selection is invalid"); return { clientId: item.clientId, articleId: item.articleId }; }); const entries = articleSubmissionItems(normalized); const byKey = new Set(entries.map(function(entry) { return entry.safe.publicationId + "\0" + entry.safe.attemptId; })); if (typeof deps.publicationLedger.listForArticles === "function") normalized.forEach(function(selection) { let records = []; try { records = deps.publicationLedger.listForArticles(selection.clientId, [selection.articleId]); } catch (_) {} records.forEach(function(record) { const latest = deps.latestAttempt(record); const key = record.publicationId + "\0" + (latest && latest.attemptId || ""); if (byKey.has(key)) return; entries.push({ safe: { clientId: selection.clientId, articleId: selection.articleId, batchId: null, targetPlatformId: record.platformId || null, publicationId: record.publicationId, attemptId: latest && latest.attemptId || null, contentHash: record.contentHash || null, status: record.status, unchanged: false, pairState: null, identityMatched: false, contentMatched: null }, item: null, batch: null, record, sidecar: null, latest }); }); });
    const queuedToCancel = []; const failedToClean = []; const publishedToClean = []; const cancelledToClean = []; const blockedItems = []; const items = entries.map(function(entry) { const state = entry.safe; if (["submitting", "submitted", "uncertain"].includes(state.status)) blockedItems.push(Object.assign({}, state, { reasonCode: "ARTICLE_SUBMISSION_ACTIVE" })); else if (state.status === "queued") { const checked = state.batchId && state.publicationId && state.attemptId && evaluateItemAction(Object.assign({}, state, { action: "cancel" })); if (checked && checked.allowed) queuedToCancel.push(Object.assign({}, state, { action: "cancel", evaluationFingerprint: checked.bindingFingerprint })); else blockedItems.push(Object.assign({}, state, { reasonCode: checked && checked.reasonCode || "PUBLICATION_RESERVATION_WITHOUT_QUEUE" })); } else if (state.status === "failed") { const checked = state.batchId && state.publicationId && state.attemptId && evaluateItemAction(Object.assign({}, state, { action: "cleanup" })); if (checked && checked.allowed) failedToClean.push(Object.assign({}, state, { action: "cleanup", evaluationFingerprint: checked.bindingFingerprint })); else if (state.batchId) blockedItems.push(Object.assign({}, state, { reasonCode: checked && checked.reasonCode || "SUBMISSION_QUEUE_CHANGED" })); } else if (["published", "cancelled"].includes(state.status) && state.batchId) { const action = state.status === "published" ? "cleanupPublishedLocal" : "cleanupCancelledLocal"; if (state.status === "published" && entry.item && entry.item.localArchive && entry.item.localArchive.status === "failed") { blockedItems.push(Object.assign({}, state, { reasonCode: "PUBLISHED_ARCHIVE_FAILED" })); return Object.assign({}, state, { sourceArticleState: "active" }); } const checked = state.publicationId && state.attemptId && evaluateItemAction(Object.assign({}, state, { action })); if (checked && checked.allowed) (state.status === "published" ? publishedToClean : cancelledToClean).push(Object.assign({}, state, { action, evaluationFingerprint: checked.bindingFingerprint })); else blockedItems.push(Object.assign({}, state, { reasonCode: checked && checked.reasonCode || "SUBMISSION_IDENTITY_CONFLICT" })); } return Object.assign({}, state, { sourceArticleState: "active" }); }); return { selections: normalized, articleCount: normalized.length, items, queuedToCancel, failedToClean, publishedToClean, cancelledToClean, blockedItems, queuedToCancelCount: queuedToCancel.length, failedToCleanCount: failedToClean.length, publishedToCleanCount: publishedToClean.length, cancelledToCleanCount: cancelledToClean.length, terminalCleanupCount: failedToClean.length + publishedToClean.length + cancelledToClean.length, canCommit: blockedItems.length === 0 };
  }
  return Object.freeze({ createReadSnapshot, getBatch, listBatches, reconcileBatch, buildActionPlan, previewArticleRemovalImpact, articleSubmissionItems, locateArticleSubmissionItem, evaluateItemAction, itemIdentity });
}
module.exports = { createSubmissionQuery };
